Repository jupyterhub/tmpauthenticator, pull requests merged in 2023-04, with the labels that each got.

#33 ci: add dependabot to bump github actions
  .github/dependabot.yaml
Labels: ci

#38 Register tmp authenticator with JupyterHub via entry_points
  README.md
  setup.py
Labels: new

#37 maint: update docstrings and import maybe_future from jupyterhub
  tmpauthenticator/__init__.py
Labels: maintenance

#35 Add RELEASE.md, associated automation, and tbump config
  .github/workflows/release.yaml
  RELEASE.md
  pyproject.toml
  setup.py
Labels: maintenance

#41 Document how to present /hub/login, make auto_login and login_service configurable
  .gitignore
  README.md
  jupyterhub_config.py
  tmpauthenticator/__init__.py
Labels: new
